name: tosfit
channels:
  - pkgs/main
dependencies:
  - pip=25.0
  - python=3.11
  - pip:
    - ipykernel==6.29.5
    - RestrictedPython==8.0
    - lexicalrichness==0.5.1
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchvision==0.21.0
    - transformers==4.51.3
    - sentence_transformers==4.1.0
    - datasets==3.3.2
    - accelerate==1.6.0
    - deepspeed==0.16
    - sentence-transformers==4.1.0
    - wandb==0.19.6
    - bert-score==0.3.13
    - biopython==1.85
    - qiskit==2.0.2
    - qiskit-aer==0.17.1
    - openfermion==1.7.1
    - openfermionpyscf==0.5
    - scipy==1.15.3
    
  - pip:
    - flash_attn